# to run both the frontend and backend services together: docker-compose up --build
# to stop the services: docker-compose down


version: '3.9'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend_service
    env_file:
      - ./Backend/.env
    ports:
      - '8000:8000'
    volumes:
      - ./Backend:/backend
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - '8501:8501'
    volumes:
      - ./Frontend:/frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge