name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        run: az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./Backend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./Frontend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_NAME }} \
            --os-type Linux \
            --ip-address public \
            --dns-name-label myappunique2023 \
            --restart-policy OnFailure \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --ports 8000 8501 \
            --containers '[
              {
                "name": "backend",
                "image": "${{ secrets.ACR_NAME }}.azurecr.io/backend:latest",
                "ports": [{"port": 8000}],
                "resources": {"requests": {"cpu": 1, "memoryInGb": 1.5}}
              },
              {
                "name": "frontend",
                "image": "${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest",
                "ports": [{"port": 8501}],
                "resources": {"requests": {"cpu": 1, "memoryInGb": 1.5}}
              }
            ]'